### ISSUE TITLE
WSL2 kali AWUS036ACM 

### ISSUE THREAD

**Issue by warlordattack** [dagg0rath/rtl8812au_fix#1]
Hello i try to make my AWUS036ACM work in Kali linux inside WSL2
could this work in WSL2 ?

┌──(root㉿ant)-[/mnt/c/Users/alexe/Desktop/temp/rtl8812au_fix]
└─# sudo ./rtl88.sh
[+] Updating System...
Ign:2 http://download.webmin.com/download/repository sarge InRelease
Hit:1 http://ftp.free.fr/pub/kali kali-rolling InRelease
Hit:3 http://download.webmin.com/download/repository sarge Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[+] Installing drivers...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
realtek-rtl88xxau-dkms is already the newest version (5.6.4.2~git20211212.3a6402e-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dkms is already the newest version (2.8.7-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fatal: destination path 'rtl8812au' already exists and is not an empty directory.
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.102.1-microsoft-standard-WSL2/build M=/mnt/c/Users/alexe/Desktop/temp/rtl8812au_fix/rtl8812au  modules
make[1]: *** /lib/modules/5.10.102.1-microsoft-standard-WSL2/build: No such file or directory.  Stop.
make: *** [Makefile:2244: modules] Error 2
install -p -m 644 88XXau.ko  /lib/modules/5.10.102.1-microsoft-standard-WSL2/kernel/drivers/net/wireless/
install: target '/lib/modules/5.10.102.1-microsoft-standard-WSL2/kernel/drivers/net/wireless/' is not a directory: No such file or directory
make: *** [Makefile:2253: install] Error 1
lo        no wireless extensions.
bond0     no wireless extensions.
dummy0    no wireless extensions.
tunl0     no wireless extensions.
sit0      no wireless extensions.
eth0      no wireless extensions.

┌──(root㉿ant)-[/mnt/c/Users/alexe/Desktop/temp/rtl8812au_fix]
└─# lsusb
Bus 002 Device 002: ID 0e8d:7612 MediaTek Inc. MT7612U 802.11a/b/g/n/ac Wireless Adapter
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

sudo dmesg
[ 3612.764770] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(3)
[ 3612.764772] vhci_hcd vhci_hcd.0: devid(196615) speed(5) speed_str(super-speed)
[ 3612.764781] vhci_hcd vhci_hcd.0: Device attached
[ 3613.109254] usb 2-1: SetAddress Request (2) to port 0
[ 3613.109258] usb 2-1: new SuperSpeed Gen 1 USB device number 2 using vhci_hcd
[ 3613.152307] usb 2-1: New USB device found, idVendor=0e8d, idProduct=7612, bcdDevice= 1.00
[ 3613.152308] usb 2-1: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[ 3613.152309] usb 2-1: Product: Wireless
[ 3613.152310] usb 2-1: Manufacturer: MediaTek Inc.
[ 3613.152310] usb 2-1: SerialNumber: 000000000

┌──(root㉿ant)-[/mnt/c/Users/alexe/Desktop/temp/rtl8812au_fix]
└─# aireplay-ng --test -i wlan0 wlan1
nl80211 not found.
Interface wlan1:
ioctl(SIOCGIFINDEX) failed: No such device

https://www.youtube.com/watch?v=hEXwOkyYNL0&t=207s&ab_channel=DavidBombal
https://www.aircrack-ng.org/doku.php?id=compatibility_drivers
https://docs.alfa.com.tw/Support/Linux/MT7612U/#kali

**Comment by dagg0rath** [comment]
Hi, thanks for the feedback.

Regarding your question about WSL2, I have to say that I'm not sure if it works there or not (since I haven't tried it yet), but considering that it uses a custom kernel, I would assume that it doesn't.

Anyway, you're trying to install a driver for an adapter that you're not using. Your ALFA AWUS036ACM uses a MediaTek MT7612U chipset. But this code installs the drivers needed for adapters like the ALFA AWUS036ACH that have a Realtek™ RTL8812AU chipset.

Hope it helped! Cheers,
dagg0rath

You can check the specs of both ALFA adapters here:
https://www.alfa.com.tw/products/awus036acm?variant=36473965936712
https://www.alfa.com.tw/products/awus036ach?variant=36473965871176

**Comment by warlordattack** [comment]
thank you, i am starting to learn linux, your reply is very helpful :)
